/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Datos.DUsuarios;
import Lógica.SLQUsuarios;
import Lógica.hash;
import javax.swing.JOptionPane;

/**
 *
 * @author NILDA
 */
public class FrmRegistrar extends javax.swing.JFrame {

    /**
     * Creates new form FrmRegistrar
     */
    public FrmRegistrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        FrmRegistrar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TxtCorreo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtContraseña = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtConfirmarContraseña = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        TxtCedula = new javax.swing.JTextField();
        TxtNumero = new javax.swing.JTextField();
        TxtDireccion = new javax.swing.JTextField();
        BtnCancelar = new javax.swing.JButton();
        BtnRegistrar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FrmRegistrar.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        jLabel3.setText("Contraseña:");

        jLabel4.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        jLabel4.setText("Confirmar contraseña:");

        TxtNombre.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        TxtNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TxtNombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 0, 102), new java.awt.Color(102, 0, 102), new java.awt.Color(102, 0, 102), new java.awt.Color(102, 0, 102)));

        jLabel1.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        jLabel1.setText("Nombre:");

        TxtCorreo.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        TxtCorreo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TxtCorreo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153)));

        jLabel2.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        jLabel2.setText("Correo electrónico:");

        TxtContraseña.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        TxtContraseña.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TxtContraseña.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 0, 102), new java.awt.Color(102, 0, 102), new java.awt.Color(102, 0, 102), new java.awt.Color(102, 0, 102)));

        jLabel7.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        jLabel7.setText("Dirección:");

        jLabel5.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        jLabel5.setText("Cédula de identidad:");

        TxtConfirmarContraseña.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        TxtConfirmarContraseña.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TxtConfirmarContraseña.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153)));

        jLabel6.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        jLabel6.setText("Número de teléfono:");

        TxtCedula.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        TxtCedula.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TxtCedula.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 0, 102), new java.awt.Color(102, 0, 102), new java.awt.Color(102, 0, 102), new java.awt.Color(102, 0, 102)));

        TxtNumero.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        TxtNumero.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TxtNumero.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153)));

        TxtDireccion.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        TxtDireccion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TxtDireccion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 0, 102), new java.awt.Color(102, 0, 102), new java.awt.Color(102, 0, 102), new java.awt.Color(102, 0, 102)));

        BtnCancelar.setBackground(new java.awt.Color(204, 204, 255));
        BtnCancelar.setFont(new java.awt.Font("Aparajita", 0, 20)); // NOI18N
        BtnCancelar.setText("Cancelar");
        BtnCancelar.setToolTipText("");
        BtnCancelar.setBorder(null);
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        BtnRegistrar.setBackground(new java.awt.Color(204, 204, 255));
        BtnRegistrar.setFont(new java.awt.Font("Aparajita", 0, 20)); // NOI18N
        BtnRegistrar.setText("Registrar");
        BtnRegistrar.setToolTipText("");
        BtnRegistrar.setBorder(null);
        BtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Aparajita", 1, 36)); // NOI18N
        jLabel10.setText("Registrar nuevo usuario");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Usuario.PNG"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Usuario.PNG"))); // NOI18N

        javax.swing.GroupLayout FrmRegistrarLayout = new javax.swing.GroupLayout(FrmRegistrar);
        FrmRegistrar.setLayout(FrmRegistrarLayout);
        FrmRegistrarLayout.setHorizontalGroup(
            FrmRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrmRegistrarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel11)
                .addGroup(FrmRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrmRegistrarLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(FrmRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FrmRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel5)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(TxtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                .addComponent(TxtCorreo)
                                .addComponent(TxtContraseña)
                                .addComponent(TxtConfirmarContraseña)
                                .addComponent(TxtCedula)
                                .addComponent(TxtNumero)
                                .addComponent(TxtDireccion))
                            .addGroup(FrmRegistrarLayout.createSequentialGroup()
                                .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(BtnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE))
                    .addGroup(FrmRegistrarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(29, 29, 29)))
                .addComponent(jLabel12)
                .addContainerGap())
        );
        FrmRegistrarLayout.setVerticalGroup(
            FrmRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrmRegistrarLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(FrmRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addGroup(FrmRegistrarLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtConfirmarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FrmRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FrmRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FrmRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        FrmPrincipal MiPrincipal = new FrmPrincipal();
        MiPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void BtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarActionPerformed

        SLQUsuarios UsSql = new SLQUsuarios();
        DUsuarios mod = new DUsuarios();

        String pass = new String(TxtContraseña.getPassword());
        String passConf = new String(TxtContraseña.getPassword());

        if (pass.equals(passConf)) {
            String NewPass = hash.sha1(pass);

            mod.setNombre(TxtNombre.getText());
            mod.setCorreo(TxtCorreo.getText());
            mod.setClaveCliente(NewPass);
            mod.setTelefono(Integer.parseInt(TxtNumero.getText()));
            mod.setCedula(Integer.parseInt(TxtCedula.getText()));
            mod.setDireccion(TxtDireccion.getText());
            
            if(TxtNombre.getText().isEmpty() || TxtCorreo.getText().isEmpty() || TxtContraseña.getText().isEmpty()||TxtNumero.getText().isEmpty()||TxtCedula.getText().isEmpty()||TxtDireccion.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe ingresar el nombre.", "ERROR", JOptionPane.ERROR);
            }else if (UsSql.registrar(mod)) {
                JOptionPane.showMessageDialog(null, "El usuario se ha registrado con exito.", "REGISTRO", JOptionPane.OK_OPTION);
                FrmPrincipal MiPrincipal = new FrmPrincipal();
                MiPrincipal.setVisible(true);
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "No se registró correctamente", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "LAS CONSTRASEÑAS NO COINCIDEN", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_BtnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnRegistrar;
    private javax.swing.JPanel FrmRegistrar;
    private javax.swing.JTextField TxtCedula;
    private javax.swing.JPasswordField TxtConfirmarContraseña;
    private javax.swing.JPasswordField TxtContraseña;
    private javax.swing.JTextField TxtCorreo;
    private javax.swing.JTextField TxtDireccion;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtNumero;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
